#!/usr/bin/env python3
"""Address-centered square service-area map generation for MARK."""
from __future__ import annotations

import json
import math
import re
from pathlib import Path
from typing import Any

import requests

NOMINATIM_URL = "https://nominatim.openstreetmap.org/search"
DEFAULT_HALF_SIZE_METERS = 3000.0
MIN_HALF_SIZE_METERS = 50.0
MAX_HALF_SIZE_METERS = 100000.0
METERS_PER_DEGREE_LATITUDE = 111_320.0


class AddressBoxError(ValueError):
    """Raised when an address box cannot be generated."""


def slug(value: str) -> str:
    """Return a filesystem-safe slug for generated address map files."""
    return re.sub(r"[^a-z0-9]+", "-", value.casefold()).strip("-") or "address"


def parse_half_size_meters(value: str | float | int | None) -> float:
    """Validate and normalize the address-box half-size in metres."""
    if value is None or str(value).strip() == "":
        return DEFAULT_HALF_SIZE_METERS
    try:
        metres = float(value)
    except (TypeError, ValueError) as exc:
        raise AddressBoxError("Address box half-size must be a number of metres.") from exc
    if metres < MIN_HALF_SIZE_METERS:
        raise AddressBoxError(
            f"Address box half-size must be at least {int(MIN_HALF_SIZE_METERS)} metres."
        )
    if metres > MAX_HALF_SIZE_METERS:
        raise AddressBoxError(
            f"Address box half-size must be no more than {int(MAX_HALF_SIZE_METERS)} metres."
        )
    return metres


def _coordinate_delta_degrees(latitude: float, half_size_meters: float) -> tuple[float, float]:
    """Return latitude and longitude deltas for a square around a WGS84 point."""
    if not -90.0 <= latitude <= 90.0:
        raise AddressBoxError("Geocoded latitude is outside the valid WGS84 range.")
    lat_delta = half_size_meters / METERS_PER_DEGREE_LATITUDE
    cos_latitude = math.cos(math.radians(latitude))
    if abs(cos_latitude) < 0.01:
        raise AddressBoxError("Address is too close to a pole to build a stable longitude box.")
    lon_delta = half_size_meters / (METERS_PER_DEGREE_LATITUDE * abs(cos_latitude))
    return lat_delta, lon_delta


def box_coordinates(latitude: float, longitude: float, half_size_meters: float) -> list[list[float]]:
    """Return a closed GeoJSON coordinate ring for a square box."""
    if not -180.0 <= longitude <= 180.0:
        raise AddressBoxError("Geocoded longitude is outside the valid WGS84 range.")
    metres = parse_half_size_meters(half_size_meters)
    lat_delta, lon_delta = _coordinate_delta_degrees(latitude, metres)
    south = max(-90.0, latitude - lat_delta)
    north = min(90.0, latitude + lat_delta)
    west = max(-180.0, longitude - lon_delta)
    east = min(180.0, longitude + lon_delta)
    return [
        [west, south],
        [east, south],
        [east, north],
        [west, north],
        [west, south],
    ]


def build_address_box_geojson(
    *,
    address: str,
    latitude: float,
    longitude: float,
    half_size_meters: float,
    display_name: str | None = None,
) -> dict[str, Any]:
    """Build a GeoJSON FeatureCollection for a square address-centered map."""
    clean_address = address.strip()
    if not clean_address:
        raise AddressBoxError("Enter an address before building an address box map.")
    metres = parse_half_size_meters(half_size_meters)
    return {
        "type": "FeatureCollection",
        "features": [
            {
                "type": "Feature",
                "properties": {
                    "name": f"Address Box - {clean_address}",
                    "purpose": "Address-centered MARK service-area box generated by the user.",
                    "warning": "Approximate geocoded box. Review visually before operational use.",
                    "address": clean_address,
                    "geocoder_display_name": display_name or clean_address,
                    "center_latitude": latitude,
                    "center_longitude": longitude,
                    "half_size_meters": metres,
                    "box_width_meters": metres * 2.0,
                    "box_height_meters": metres * 2.0,
                },
                "geometry": {
                    "type": "Polygon",
                    "coordinates": [box_coordinates(latitude, longitude, metres)],
                },
            }
        ],
    }


def geocode_address(
    address: str,
    *,
    timeout: float = 20.0,
    user_agent: str = "MARK-chp-alerter address-box geocoder",
) -> tuple[float, float, str]:
    """Resolve an address to latitude, longitude, and geocoder display name."""
    clean_address = address.strip()
    if not clean_address:
        raise AddressBoxError("Enter an address before geocoding.")
    response = requests.get(
        NOMINATIM_URL,
        params={"q": clean_address, "format": "jsonv2", "limit": 1},
        headers={"User-Agent": user_agent},
        timeout=timeout,
    )
    response.raise_for_status()
    payload = response.json()
    if not isinstance(payload, list) or not payload:
        raise AddressBoxError(f"No geocoding result found for: {clean_address}")
    result = payload[0]
    try:
        latitude = float(result["lat"])
        longitude = float(result["lon"])
    except (KeyError, TypeError, ValueError) as exc:
        raise AddressBoxError("Geocoder returned a result without valid coordinates.") from exc
    display_name = str(result.get("display_name") or clean_address)
    return latitude, longitude, display_name


def generated_address_box_path(root: Path, address: str) -> Path:
    """Return the runtime path where a generated address box should be stored."""
    return root / "runtime" / "address_maps" / f"{slug(address)}-address-box.geojson"


def write_address_box_geojson(path: Path, payload: dict[str, Any]) -> Path:
    """Write an address-box GeoJSON payload and return the written path."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    return path
